<a href="https://colab.research.google.com/github/ly-wonderful/Pytorch-Training-and-Exercises/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:

# !pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

In [43]:
import torch
torch.__version__

'2.5.1+cu121'

In [44]:
scalar = torch.tensor(7)
print(scalar), scalar.ndim

tensor(7)


(None, 0)

In [45]:
scalar.item()

7

In [46]:
vector = torch.tensor([7, 7])

In [47]:
vector.ndim

1

In [48]:
vector.shape

torch.Size([2])

In [49]:
  MATRIX = torch.tensor([[7, 8],
                         [9, 10]])
  MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [50]:
MATRIX.ndim

2

In [51]:
MATRIX.shape

torch.Size([2, 2])

In [52]:
TENSOR = torch.rand(1, 3, 3)
TENSOR

tensor([[[0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696]]])

In [53]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels. colour channels could be at front.
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [54]:
zeros = torch.zeros(3, 4)
ones = torch.ones(3, 4)

ones.dtype

torch.float32

In [55]:
### Creating a range of tensors and tensors-like
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
# 3 most common issues with pytorch
## 1. Tensors not right datatype - "tensor.dytpe"
## 2. Tensors not right shape - "tensor.shape"
## 3. Tensors not on the right device - "tensor.device"

# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"


float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device=device,
                               requires_grad=False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [58]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [59]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [60]:
### Tensor Operations

tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor * 10, tensor - 10.0, torch.mul(tensor, 10)

(tensor([11, 12, 13]),
 tensor([10, 20, 30]),
 tensor([-9., -8., -7.]),
 tensor([10, 20, 30]))

In [61]:
torch.matmul(tensor, tensor)

tensor(14)

In [62]:
# Tensor Aggregation (min, max, mean, sum)
x = torch.arange(0, 100, 10)
torch.min(x), torch.max(x), x.dtype, x.sum()

(tensor(0), tensor(90), torch.int64, tensor(450))

In [63]:
torch.mean(x.type(torch.float16)), torch.mean(x, dtype=torch.float32).item()

(tensor(45., dtype=torch.float16), 45.0)

In [64]:
# x.argmin() Find the minimus index of a tensor
# x.argmax() maximus index



### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshape
* View - reshape and keep the same memory
* Stack - torch.stack(), torch.vstack(), torch.hstack()
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [65]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:
x_reshaped = x.reshape(3,3,1)
x_reshaped, x_reshaped.shape

(tensor([[[1.],
          [2.],
          [3.]],
 
         [[4.],
          [5.],
          [6.]],
 
         [[7.],
          [8.],
          [9.]]]),
 torch.Size([3, 3, 1]))

In [67]:
z = x.view(1, 9) # change z will change x, because they point to the same memory

In [68]:
x_stacked = torch.stack([x, x, x, x ], dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [69]:
x_reshaped, x_reshaped.shape

(tensor([[[1.],
          [2.],
          [3.]],
 
         [[4.],
          [5.],
          [6.]],
 
         [[7.],
          [8.],
          [9.]]]),
 torch.Size([3, 3, 1]))

In [70]:
# remove all single dimensions from tensor
x_squeezed = torch.squeeze(x_reshaped)
x_squeezed, x_squeezed.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [71]:
x_unsqueezed = x_squeezed.unsqueeze(dim=2)
x_unsqueezed, x_unsqueezed.shape


(tensor([[[1.],
          [2.],
          [3.]],
 
         [[4.],
          [5.],
          [6.]],
 
         [[7.],
          [8.],
          [9.]]]),
 torch.Size([3, 3, 1]))

In [72]:
x_original = torch.rand(size=(224, 224, 3))
x_permute = x_original.permute(2, 0, 1)
x_permute.shape

torch.Size([3, 224, 224])

In [73]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor, array.dtype, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'),
 torch.float64)

In [74]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [75]:
numpy_tensor.dtype

dtype('float32')

In [76]:
## Reproducability (trying to take random out of random)

In [77]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [78]:
random_tensor2 = torch.rand(3, 4)
random_tensor2

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [79]:
torch.manual_seed(RANDOM_SEED)
random_tensor3 = torch.rand(3, 4)
random_tensor3

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [80]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [1]:
import torch
torch.cuda.is_available()

True

In [3]:
# Putting tensors (and models) on the GPU
tensor = torch.tensor([1, 2, 3], device='cuda')
tensor.device


device(type='cuda', index=0)

In [4]:
tensor_on_gpu = tensor.to('cuda')
tensor_on_gpu.device

device(type='cuda', index=0)

In [6]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [7]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.device

device(type='cpu')